### ISSUE TITLE
Support InfluxDB 1.8

### ISSUE THREAD

**Issue by fkjellberg** [1p4pk/bahir-flink#45]
Hi!

I've been testing this connector and tried to run it against InfluxDB 1.8 but I had to patch the connector for it to work properly.

InfluxDB 1.8 supports query and write from the InfluxDB 2.0 API (https://docs.influxdata.com/influxdb/v1.8/tools/api/#influxdb-20-api-compatibility-endpoints) but not the new authentication API which is currently used by this connector. It would be great if the connector can support both InfluxDB 1.8 and 2.0 either by configuration or making it possible to supply your own preconfigured InfluxDBClient to the InfluxDBSink.builder() instance. A client compatible with InfluxDB 1.8 can be created by calling InfluxDBClientFactory.createV1() and the connector works fine for me if I patch it to call this method to create the InfluxDBClient.

**Comment by 1p4pk** [comment]
Hi @fkjellberg,

Nice that you have been working with this connector. It should be merged into the Apache Bahir Repository quite soon. However, this connector was not meant to support any older versions. The reason is that Apache Bahir already has an older [connector](https://github.com/apache/bahir-flink/tree/master/flink-connector-influxdb) that supports the 1.X API from InfluxDB. Does it solve your Problems?

Best,
Leon

**Comment by fkjellberg** [comment]
Hi @1p4pk,

Yes, I tried the existing connector, but this one has better features and performance. :-) Your connector works fine with 1.8 unless you enable authentication. I agree that it's more important to get this merged into the Apache git repo and I saw that the PR is already approved, so we can close this ticket and I will open a new one in Apache's Jira once it's fully merged.

Really looking forward having this connector as part of Apache Bahir. Thanks for your hard work building it!


/Fredrik
